 ./download.py
2025-09-19 12:21:37,681 INFO === DIBBS download run starting for 250918 ===
2025-09-19 12:21:38,601 INFO HEAD https://dibbs2.bsm.dla.mil/Downloads/RFQ/Archive/bq250918.zip -> 404 None 0
2025-09-19 12:21:38,601 WARNING HEAD for BQ ZIP failed; attempting GET anyway.
2025-09-19 12:21:38,601 INFO Downloading BQ ZIP: https://dibbs2.bsm.dla.mil/Downloads/RFQ/Archive/bq250918.zip
2025-09-19 12:21:39,591 INFO Saved staging\bq250918.zip (165504 bytes)
2025-09-19 12:21:39,592 INFO ZIP contains: ['bq250918.txt', 'as250918.txt']
2025-09-19 12:21:39,600 INFO Extracted bq250918.txt -> staging\bq250918.txt
2025-09-19 12:21:39,604 INFO Extracted as250918.txt -> staging\as250918.txt
2025-09-19 12:21:39,606 INFO Attempting IN TXT: https://dibbs2.bsm.dla.mil/Downloads/RFQ/Archive/in250918.txt
2025-09-19 12:21:39,673 INFO HEAD https://dibbs2.bsm.dla.mil/Downloads/RFQ/Archive/in250918.txt -> 404 None 0
2025-09-19 12:21:39,686 WARNING HEAD for IN failed; attempting GET anyway.
2025-09-19 12:21:40,641 INFO Saved staging\in250918.txt (606482 bytes)
[FATAL] OSError(18, 'The system cannot move the file to a different disk drive')
Traceback (most recent call last):
  File "C:\Users\Arturo\Desktop\downloadDibbs\download.py", line 255, in <module>
    main()
  File "C:\Users\Arturo\Desktop\downloadDibbs\download.py", line 247, in main
    src.replace(dst)
  File "C:\Users\Arturo\Desktop\Lib\pathlib.py", line 1376, in replace
    os.replace(self, target)
OSError: [WinError 17] The system cannot move the file to a different disk drive: 'staging\\bq250918.txt' -> '\\\\MDF-SERVER-02\\Database\\MDF database files\\Automated Imports\\dibbs\\bq250918.txt'